import { McpServer } from "@modelcontextprotocol/server";
import { createMcpHandler } from "agents/mcp/server";
import { z } from "zod";

type R2 = { put(key:string,v:any,o?:any):Promise<void>; get(key:string):Promise<any> };
type Env = { XKIRO_API_KEY?:string; MCP_ACCESS_TOKEN?:string; UPLOADS?:R2 };
const API="https://api.xkiro.com", DEFAULT_MODEL="sensenova/sensenova-u1.5-lite", MODELS=["sensenova/sensenova-u1.5-lite","openai/gpt-image-2.5"] as const;
const TTL=30*60*1000, MAX=20*1024*1024, types=["image/jpeg","image/png","image/webp","image/gif"];
const model=z.enum(MODELS).optional();
function eq(a:string,b:string){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function auth(r:Request,e:Env){const x=e.MCP_ACCESS_TOKEN?.trim();if(!x)return false;for(const v of [r.headers.get("x-api-key"),r.headers.get("X-MCP-Password"),r.headers.get("MCP-Access-Token")])if(v&&eq(v.trim(),x))return true;const m=(r.headers.get("Authorization")||"").match(/^Bearer\s+(.+)$/i);return !!m&&eq(m[1].trim(),x)}
async function json(e:Env,p:string,i?:RequestInit){if(!e.XKIRO_API_KEY)throw Error("XKIRO_API_KEY is not configured");const r=await fetch(API+p,{...i,headers:{Accept:"application/json","Content-Type":"application/json",Authorization:`Bearer ${e.XKIRO_API_KEY}`,...i?.headers}});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw Error(`xKiro HTTP ${r.status}: ${JSON.stringify(d)}`);return d}
async function edit(e:Env,a:any){const s=await fetch(a.image_url);if(!s.ok)throw Error(`Could not fetch source image: HTTP ${s.status}`);const ct=(s.headers.get("content-type")||"").split(";")[0].toLowerCase();if(!types.includes(ct))throw Error("source URL did not return a supported image");const f=new FormData();f.append("image",new Blob([await s.arrayBuffer()],{type:ct}),`source.${ct==="image/jpeg"?"jpg":ct.split("/")[1]}`);f.append("prompt",a.prompt);f.append("model",a.model||DEFAULT_MODEL);if(a.size)f.append("size",a.size);if(a.n!==undefined)f.append("n",String(a.n));const r=await fetch(API+"/v1/images/edits",{method:"POST",headers:{Authorization:`Bearer ${e.XKIRO_API_KEY}`,Accept:"application/json"},body:f});const t=await r.text();let d:any;try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok)throw Error(`xKiro edit HTTP ${r.status}: ${JSON.stringify(d)}`);return d}
function mcp(e:Env){const s=new McpServer({name:"xkiro-mcp",version:"2.3.0"});s.registerTool("generate_image",{description:"Submit an asynchronous image-generation job to xKiro.",inputSchema:{prompt:z.string().min(1),model,n:z.number().optional(),size:z.string().optional(),style:z.string().optional()}},async({prompt,model,n,size,style})=>({content:[{type:"text",text:JSON.stringify(await json(e,"/v1/images/generations",{method:"POST",body:JSON.stringify({prompt,model:model||DEFAULT_MODEL,n,size,style})}))}]}));s.registerTool("edit_image",{description:"Edit an existing image from an HTTPS image URL.",inputSchema:{image_url:z.string().url(),prompt:z.string().min(1),model,size:z.string().optional(),n:z.number().optional()}},async a=>({content:[{type:"text",text:JSON.stringify(await edit(e,a))}]}));s.registerTool("get_image_job",{description:"Retrieve an xKiro image-generation job by id.",inputSchema:{id:z.string().min(1)}},async({id})=>({content:[{type:"text",text:JSON.stringify(await json(e,`/v1/images/generations/${encodeURIComponent(id)}`))}]}));s.registerTool("list_image_jobs",{description:"List recent xKiro image-generation jobs.",inputSchema:{before:z.string().optional()}},async({before})=>({content:[{type:"text",text:JSON.stringify(await json(e,`/v1/images/generations${before?`?before=${encodeURIComponent(before)}`:""}`))}]}));s.registerTool("get_upload_slot",{description:"Open the temporary image upload page; no password required.",inputSchema:{}},async()=>({content:[{type:"text",text:JSON.stringify({upload_page:"/upload",expires_in_minutes:30,password_required:false})}]}));return s}
function page(){return `<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>رفع صورة مؤقتة</title><style>body{font-family:system-ui;background:#111;color:#eee;max-width:560px;margin:auto;padding:24px}main{background:#1d1d1d;padding:20px;border-radius:16px}input,button{font:inherit;padding:12px;border-radius:10px;border:1px solid #555;margin-top:12px;width:100%;box-sizing:border-box}button{background:#5b8cff;color:white;border:0}#out{word-break:break-all;margin-top:16px}small{color:#aaa}</style><main><h2>رفع صورة مؤقتة</h2><p>بدون كلمة سر. الرابط صالح 30 دقيقة فقط.</p><input id="file" type="file" accept="image/jpeg,image/png,image/webp,image/gif"><button id="go">رفع الصورة ونسخ الرابط</button><div id="out"></div></main><script>const $=x=>document.getElementById(x);$('go').onclick=async()=>{const f=$('file').files[0];if(!f)return $('out').textContent='اختر صورة أولاً';$('go').disabled=true;$('out').textContent='جارٍ الرفع...';try{const r=await fetch(location.pathname,{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Type':f.type},body:f});const d=await r.json();if(!r.ok)throw Error(d.error||'فشل الرفع');try{await navigator.clipboard.writeText(d.url)}catch{}$('out').innerHTML='<b>تم الرفع ونسخ الرابط.</b><br><a href="'+d.url+'" target="_blank">'+d.url+'</a><br><small>ينتهي بعد 30 دقيقة</small>'}catch(e){$('out').textContent=e.message}finally{$('go').disabled=false}};</script></html>`}
async function side(r:Request,e:Env,u:URL){if(u.pathname==="/upload"||u.pathname==="/upload/"){if(r.method==="GET")return new Response(page(),{headers:{"Content-Type":"text/html;charset=utf-8","Cache-Control":"no-store"}});if(r.method!=="POST")return new Response("Method not allowed",{status:405});if(!e.UPLOADS)return new Response(JSON.stringify({error:"R2 bucket hi-uploads is not bound"}),{status:503,headers:{"Content-Type":"application/json"}});const ct=(r.headers.get("X-File-Type")||"").toLowerCase();if(!types.includes(ct))return new Response(JSON.stringify({error:"Unsupported image type"}),{status:400});const b=await r.arrayBuffer();if(!b.byteLength||b.byteLength>MAX)return new Response(JSON.stringify({error:"Image must be between 1 byte and 20MB"}),{status:400});const ext=ct==="image/jpeg"?"jpg":ct.split("/")[1],key=`temporary/${crypto.randomUUID()}.${ext}`,expiresAt=Date.now()+TTL;await e.UPLOADS.put(key,b,{httpMetadata:{contentType:ct},customMetadata:{expiresAt:String(expiresAt)}});return new Response(JSON.stringify({url:`https://${u.host}/uploads/${key}`,expiresAt:new Date(expiresAt).toISOString(),expiresInMinutes:30}),{headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}if(u.pathname.startsWith("/uploads/")){if(r.method!=="GET"&&r.method!=="HEAD")return new Response("Method not allowed",{status:405});if(!e.UPLOADS)return new Response("Uploads not enabled",{status:503});const key=u.pathname.slice(9);if(!key||key.includes(".."))return new Response("Not found",{status:404});const o=await e.UPLOADS.get(key);if(!o)return new Response("Not found",{status:404});const x=Number(o.customMetadata?.expiresAt||0);if(!x||Date.now()>=x)return new Response("Expired",{status:410,headers:{"Cache-Control":"no-store"}});const h=new Headers({"Content-Type":o.httpMetadata?.contentType||"application/octet-stream","Cache-Control":"no-store","Access-Control-Allow-Origin":"*"});return new Response(r.method==="HEAD"?null:o.body,{headers:h})}return new Response("Not found",{status:404})}
export default{fetch(r:Request,e:Env,c:ExecutionContext){const u=new URL(r.url);if(u.pathname==="/upload"||u.pathname==="/upload/"||u.pathname.startsWith("/uploads/"))return side(r,e,u);if(u.pathname==="/health")return new Response(JSON.stringify({status:"ok",version:"2.3.0"}),{headers:{"Content-Type":"application/json"}});if(u.pathname!=="/mcp"&&u.pathname!=="/mcp/")return new Response("Not found",{status:404});if(!e.MCP_ACCESS_TOKEN)return new Response(JSON.stringify({error:"MCP_ACCESS_TOKEN is not configured"}),{status:503});if(r.method!=="OPTIONS"&&!auth(r,e))return new Response(JSON.stringify({error:"Unauthorized"}),{status:401});return createMcpHandler(()=>mcp(e))(r,e,c)}} satisfies ExportedHandler<Env>;
